// Sample data for Spanish-speaking Latin American sales team

export const metricsData = {
  totalAcumulado: "$847,500",
  transacciones: "156",
  aovTratoCerrado: "$5,432",
  feccu: "$312,000",
  feccp: "$185,500",
  beccu: "$215,000",
  beccp: "$135,000",
}

export const dailyEvolutionData = [
  { date: "1 Ene", amount: 12500 },
  { date: "2 Ene", amount: 18200 },
  { date: "3 Ene", amount: 15800 },
  { date: "4 Ene", amount: 22400 },
  { date: "5 Ene", amount: 19600 },
  { date: "6 Ene", amount: 28500 },
  { date: "7 Ene", amount: 24300 },
  { date: "8 Ene", amount: 31200 },
  { date: "9 Ene", amount: 27800 },
  { date: "10 Ene", amount: 35400 },
  { date: "11 Ene", amount: 29100 },
  { date: "12 Ene", amount: 38700 },
  { date: "13 Ene", amount: 33500 },
  { date: "14 Ene", amount: 42100 },
]

export const agendasData = [
  {
    id: "1",
    nombre: "María González",
    telefono: "+52 55 1234 5678",
    instagram: "@maria.glez",
    fechaAgenda: "2024-01-15",
    fechaCloser: "2024-01-16",
    edad: 34,
    closer: "Carlos Mendoza",
    setter: "Ana Ruiz",
    calificacion: "A" as const,
    fuente: "Instagram Ads",
    estado: "Show" as const,
    cerro: true,
    operacion: "Elite Coaching",
    ccDia1: "$2,500",
    linkFathom: "https://fathom.video/123",
  },
  {
    id: "2",
    nombre: "Roberto Sánchez",
    telefono: "+54 11 9876 5432",
    instagram: "@rob_sanchez",
    fechaAgenda: "2024-01-15",
    fechaCloser: "2024-01-16",
    edad: 28,
    closer: "Luis Pérez",
    setter: "Carmen López",
    calificacion: "B" as const,
    fuente: "Referido",
    estado: "Show" as const,
    cerro: true,
    operacion: "Programa Premium",
    ccDia1: "$1,800",
    linkFathom: "https://fathom.video/124",
  },
  {
    id: "3",
    nombre: "Patricia Herrera",
    telefono: "+57 310 555 1234",
    instagram: "@paty_herrera",
    fechaAgenda: "2024-01-14",
    fechaCloser: "2024-01-15",
    edad: 41,
    closer: "Carlos Mendoza",
    setter: "Ana Ruiz",
    calificacion: "A" as const,
    fuente: "Webinar",
    estado: "Show" as const,
    cerro: true,
    operacion: "Elite Coaching",
    ccDia1: "$3,200",
    linkFathom: "https://fathom.video/125",
  },
  {
    id: "4",
    nombre: "Jorge Martínez",
    telefono: "+52 33 4567 8901",
    instagram: "@jorge.mtz",
    fechaAgenda: "2024-01-14",
    fechaCloser: "2024-01-15",
    edad: 36,
    closer: "Luis Pérez",
    setter: "Carmen López",
    calificacion: "C" as const,
    fuente: "Facebook Ads",
    estado: "No Show" as const,
    cerro: false,
    operacion: "-",
    ccDia1: "-",
    linkFathom: "https://fathom.video/126",
  },
  {
    id: "5",
    nombre: "Lucía Ramírez",
    telefono: "+54 11 2345 6789",
    instagram: "@lu_ramirez",
    fechaAgenda: "2024-01-13",
    fechaCloser: "2024-01-14",
    edad: 29,
    closer: "Carlos Mendoza",
    setter: "Ana Ruiz",
    calificacion: "B" as const,
    fuente: "Instagram Organic",
    estado: "Show" as const,
    cerro: false,
    operacion: "-",
    ccDia1: "-",
    linkFathom: "https://fathom.video/127",
  },
  {
    id: "6",
    nombre: "Fernando Torres",
    telefono: "+57 315 777 8888",
    instagram: "@fer.torres",
    fechaAgenda: "2024-01-13",
    fechaCloser: "2024-01-14",
    edad: 45,
    closer: "Luis Pérez",
    setter: "Carmen López",
    calificacion: "D" as const,
    fuente: "Cold DM",
    estado: "Cancelado" as const,
    cerro: false,
    operacion: "-",
    ccDia1: "-",
    linkFathom: "https://fathom.video/128",
  },
  {
    id: "7",
    nombre: "Andrea Morales",
    telefono: "+52 55 8765 4321",
    instagram: "@and_morales",
    fechaAgenda: "2024-01-12",
    fechaCloser: "2024-01-13",
    edad: 32,
    closer: "Carlos Mendoza",
    setter: "Ana Ruiz",
    calificacion: "A" as const,
    fuente: "Referido",
    estado: "Show" as const,
    cerro: true,
    operacion: "Programa Premium",
    ccDia1: "$2,100",
    linkFathom: "https://fathom.video/129",
  },
  {
    id: "8",
    nombre: "Diego Castro",
    telefono: "+54 11 5555 6666",
    instagram: "@diego.castro",
    fechaAgenda: "2024-01-12",
    fechaCloser: "2024-01-13",
    edad: 38,
    closer: "Luis Pérez",
    setter: "Carmen López",
    calificacion: "B" as const,
    fuente: "Instagram Ads",
    estado: "Show" as const,
    cerro: true,
    operacion: "Elite Coaching",
    ccDia1: "$2,800",
    linkFathom: "https://fathom.video/130",
  },
]

export const cuotasData = [
  {
    id: "1",
    cliente: "María González",
    operacion: "Elite Coaching",
    montoCuota: "$1,500",
    fechaVencimiento: "2024-02-01",
    estado: "Pendiente" as const,
    medioPago: "Stripe",
  },
  {
    id: "2",
    cliente: "Roberto Sánchez",
    operacion: "Programa Premium",
    montoCuota: "$900",
    fechaVencimiento: "2024-01-25",
    estado: "Pagado" as const,
    medioPago: "Transferencia",
  },
  {
    id: "3",
    cliente: "Patricia Herrera",
    operacion: "Elite Coaching",
    montoCuota: "$1,600",
    fechaVencimiento: "2024-01-20",
    estado: "Vencido" as const,
    medioPago: "Stripe",
  },
  {
    id: "4",
    cliente: "Andrea Morales",
    operacion: "Programa Premium",
    montoCuota: "$1,050",
    fechaVencimiento: "2024-02-05",
    estado: "Pendiente" as const,
    medioPago: "PayPal",
  },
  {
    id: "5",
    cliente: "Diego Castro",
    operacion: "Elite Coaching",
    montoCuota: "$1,400",
    fechaVencimiento: "2024-02-10",
    estado: "Pendiente" as const,
    medioPago: "Stripe",
  },
  {
    id: "6",
    cliente: "Laura Jiménez",
    operacion: "Mentoria VIP",
    montoCuota: "$2,000",
    fechaVencimiento: "2024-01-18",
    estado: "Pagado" as const,
    medioPago: "Transferencia",
  },
  {
    id: "7",
    cliente: "Miguel Ángel Vega",
    operacion: "Programa Premium",
    montoCuota: "$950",
    fechaVencimiento: "2024-01-15",
    estado: "Vencido" as const,
    medioPago: "Stripe",
  },
  {
    id: "8",
    cliente: "Sofía Delgado",
    operacion: "Elite Coaching",
    montoCuota: "$1,500",
    fechaVencimiento: "2024-02-15",
    estado: "Pendiente" as const,
    medioPago: "PayPal",
  },
]

export const pipelineData = {
  "Lead Asignado": [
    { id: "1", nombre: "Valentina Rojas", empresa: "Marketing Digital", valor: "$4,500", dias: 2 },
    { id: "2", nombre: "Sebastián Flores", empresa: "E-commerce", valor: "$3,200", dias: 1 },
    { id: "3", nombre: "Camila Reyes", empresa: "Coaching Personal", valor: "$5,800", dias: 3 },
  ],
  "Triage": [
    { id: "4", nombre: "Mateo Vargas", empresa: "Consultoría", valor: "$6,200", dias: 4 },
    { id: "5", nombre: "Isabella Muñoz", empresa: "Fitness Online", valor: "$3,800", dias: 2 },
  ],
  "Confirmado": [
    { id: "6", nombre: "Santiago Herrera", empresa: "Tech Startup", valor: "$7,500", dias: 3 },
    { id: "7", nombre: "Mariana Díaz", empresa: "Agencia Creativa", valor: "$4,200", dias: 5 },
    { id: "8", nombre: "Emiliano Cruz", empresa: "Real Estate", valor: "$8,000", dias: 2 },
  ],
  "Presentado": [
    { id: "9", nombre: "Renata Medina", empresa: "Health & Wellness", valor: "$5,500", dias: 1 },
    { id: "10", nombre: "Nicolás Romero", empresa: "SaaS", valor: "$9,200", dias: 4 },
  ],
  "Fee/Señado": [
    { id: "11", nombre: "Antonella Gómez", empresa: "Inversiones", valor: "$12,000", dias: 2 },
  ],
  "Cerrado ✅": [
    { id: "12", nombre: "Tomás Navarro", empresa: "E-learning", valor: "$6,800", dias: 0 },
    { id: "13", nombre: "Julieta Campos", empresa: "Beauty Brand", valor: "$4,900", dias: 0 },
  ],
}

export const equipoData = [
  {
    id: "1",
    nombre: "Carlos Mendoza",
    foto: "CM",
    cashCollected: "$187,500",
    tasaCierre: 68,
    unidadesCerradas: 42,
    strikes: 0,
  },
  {
    id: "2",
    nombre: "Luis Pérez",
    foto: "LP",
    cashCollected: "$156,200",
    tasaCierre: 62,
    unidadesCerradas: 35,
    strikes: 1,
  },
  {
    id: "3",
    nombre: "Ana Ruiz",
    foto: "AR",
    cashCollected: "$134,800",
    tasaCierre: 58,
    unidadesCerradas: 28,
    strikes: 0,
  },
  {
    id: "4",
    nombre: "Carmen López",
    foto: "CL",
    cashCollected: "$112,400",
    tasaCierre: 55,
    unidadesCerradas: 24,
    strikes: 2,
  },
  {
    id: "5",
    nombre: "Miguel Torres",
    foto: "MT",
    cashCollected: "$98,600",
    tasaCierre: 52,
    unidadesCerradas: 21,
    strikes: 1,
  },
]
