-- ═══════════════════════════════════════════════════════════════════
-- ESQUEMA BASE (reconstruido)
-- La plantilla original trae 25 migraciones que modifican tablas que
-- ninguna de ellas crea (agendas, pagos, clientes, planes_pago,
-- plan_pago_items, team_members…). Este archivo crea esas tablas base con
-- las columnas que usa el código (lib/supabase.ts + rutas /api) para que
-- las migraciones originales apliquen en orden. Todo "add column" posterior
-- es "if not exists", así que no choca. Si se consigue el volcado real del
-- esquema original, reemplazar este archivo por ese.
-- ═══════════════════════════════════════════════════════════════════

create extension if not exists "pgcrypto";

-- ── equipo / accesos ─────────────────────────────────────────────────
create table if not exists public.team_members (
  id bigint generated by default as identity primary key,
  email text not null unique,
  nombre text,
  rol text,
  estado text not null default 'pendiente',
  cuenta text,
  avatar text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ── agendas (leads con llamada) ──────────────────────────────────────
create table if not exists public.agendas (
  id uuid primary key default gen_random_uuid(),
  nombre text,
  email text,
  telefono text,
  instagram text,
  puntos_contacto text,
  fecha_agenda date,
  fecha_closer date,
  fecha_lead date,
  edad text,
  closer text,
  cuenta text,
  setter text,
  calificacion text,
  calificacion_real text,
  motivo_calificacion_real text,
  angulo_entrada text,
  campaign_id text,
  ad_id text,
  creative_id text,
  fuente text,
  ocupacion text,
  manychat text,
  resumen_chat text,
  calificaba_realmente text,
  call_confirmer text,
  info_call_triage text,
  recurso text,
  show boolean not null default false,
  cerro boolean not null default false,
  estado text,
  motivo_no_cierre text,
  seguimiento_estado text,
  seguimiento_fecha date,
  seguimiento_nota text,
  seguimiento_responsable text,
  seguimiento_actualizado_at timestamptz,
  link_fathom text,
  operacion text,
  plan_de_pago text,
  tipo_cierre text,
  medio_de_pago text,
  comprobante text,
  cc_dia_1 numeric,
  fecha_tc date,
  fecha_baja date,
  ia_analisis text,
  problema_actual text,
  tiempo_problema text,
  intentos_previos text,
  motivo_urgencia text,
  ingresos text,
  inversion text,
  rescatado boolean,
  motivo_inclusion text,
  calificacion_crm_original text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists agendas_fecha_agenda_idx on public.agendas (fecha_agenda);
create index if not exists agendas_closer_idx on public.agendas (closer);
create index if not exists agendas_telefono_idx on public.agendas (telefono);

-- ── pagos ────────────────────────────────────────────────────────────
create table if not exists public.pagos (
  id uuid primary key default gen_random_uuid(),
  fecha date,
  fecha_alta date,
  fecha_baja date,
  cliente text,
  telefono text,
  tipo text,
  operacion text,
  closer text,
  setter text,
  calificacion text,
  monto numeric,
  cc_ars numeric,
  medio_de_pago text,
  tipo_cambio_usd numeric,
  comprobante text,
  ppp text,
  fuente text,
  contenido_contestado text,
  otras_comisiones text,
  control text,
  es_reactivacion boolean,
  voided_at timestamptz,
  voided_by text,
  void_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists pagos_fecha_idx on public.pagos (fecha);
create index if not exists pagos_cliente_idx on public.pagos (cliente);

-- ── planes de pago y sus cuotas ──────────────────────────────────────
create table if not exists public.planes_pago (
  id uuid primary key default gen_random_uuid(),
  cliente text,
  telefono text,
  operacion text,
  closer text,
  setter text,
  calificacion text,
  fuente text,
  contenido_contestado text,
  fecha_alta date,
  fecha_baja date,
  concepto text,
  estado text not null default 'activo',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.plan_pago_items (
  id uuid primary key default gen_random_uuid(),
  plan_id uuid not null references public.planes_pago(id) on delete cascade,
  orden integer not null default 1,
  concepto text,
  numero_cuota integer,
  monto numeric,
  fecha_planeada date,
  medio_de_pago text,
  da_acceso boolean not null default false,
  estado text not null default 'pendiente',
  pago_id uuid references public.pagos(id) on delete set null,
  comprobante text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists plan_pago_items_plan_idx on public.plan_pago_items (plan_id);
create index if not exists plan_pago_items_fecha_idx on public.plan_pago_items (fecha_planeada);

-- ── cuotas (vista simple de cobranza) ────────────────────────────────
create table if not exists public.cuotas (
  id bigint generated by default as identity primary key,
  cliente text not null,
  operacion text,
  monto numeric not null default 0,
  fecha_vencimiento date,
  estado text not null default 'pendiente',
  medio_de_pago text,
  closer text,
  plan_de_pago text,
  monto_cobrado numeric,
  telefono text,
  created_at timestamptz not null default now()
);

-- ── clientes ─────────────────────────────────────────────────────────
create table if not exists public.clientes (
  id bigint generated by default as identity primary key,
  nombre text not null,
  calificacion text,
  telefono text,
  fecha_ingreso date,
  duracion text,
  fecha_baja date,
  fecha_proxima_call date,
  fecha_3ra_call date,
  fecha_4ta_call date,
  medio_de_pago text,
  operacion_original text,
  pitch text,
  fecha_primer_call date,
  estado text,
  operacion_resell text,
  medio_pago_resell text,
  monto_con_descuento text,
  etapa text,
  link_call_onboarding text,
  health_status text,
  last_contact_at timestamptz,
  next_action text,
  next_action_at timestamptz,
  backend_priority text,
  backend_status text,
  backend_potential_usd numeric,
  backend_offer text,
  backend_owner text,
  lifecycle_notes text,
  last_observed_activity_at timestamptz,
  inactivity_days integer,
  engagement_signal text,
  engagement_signal_reason text,
  renewal_status text,
  renewal_potential_usd numeric,
  renewal_probability numeric,
  renewal_loss_reason text,
  merged_into_client_id bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists clientes_nombre_idx on public.clientes (nombre);
create index if not exists clientes_telefono_idx on public.clientes (telefono);

-- ── equipo: strikes ──────────────────────────────────────────────────
create table if not exists public.strikes (
  id bigint generated by default as identity primary key,
  nombre text not null,
  rol text,
  count integer not null default 0,
  updated_at timestamptz not null default now()
);

-- ── finanzas simples: gastos, payroll, métricas manuales ─────────────
create table if not exists public.gastos (
  id bigint generated by default as identity primary key,
  fecha date,
  mes text,
  mes_orden integer,
  monto_usd numeric not null default 0,
  tipo_gasto text,
  descripcion text,
  created_at timestamptz not null default now()
);

create table if not exists public.payroll (
  id bigint generated by default as identity primary key,
  mes text,
  mes_orden integer,
  persona text,
  rol text,
  total_usd numeric not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.metricas_manual (
  id bigint generated by default as identity primary key,
  tipo text not null,
  valor numeric,
  semana text,
  persona text,
  mes text,
  created_at timestamptz not null default now()
);

create table if not exists public.finance_sale_distributions (
  id bigint generated by default as identity primary key,
  occurred_on date not null default current_date,
  partner_key text,
  amount numeric not null default 0,
  currency text default 'USD',
  notes text,
  created_at timestamptz not null default now()
);

-- ── operaciones: caché, colas y observabilidad ───────────────────────
create table if not exists public.crm_metric_cache (
  cache_key text primary key,
  value jsonb,
  computed_at timestamptz not null default now(),
  expires_at timestamptz,
  computation_ms integer,
  row_count integer,
  last_error text,
  source_cursor text
);

create table if not exists public.crm_notification_outbox (
  id bigint generated by default as identity primary key,
  status text not null default 'pending',
  source_issue_key text,
  assigned_role text,
  account_id text,
  payload jsonb,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.crm_client_growth_queue (
  id bigint generated by default as identity primary key,
  client_id bigint,
  client_name text,
  sort_score numeric not null default 0,
  reason text,
  metadata jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.crm_api_observations (
  id bigint generated by default as identity primary key,
  route text,
  provider text,
  status_code integer,
  duration_ms integer,
  error_code text,
  error text,
  metadata jsonb,
  observed_at timestamptz not null default now()
);

create table if not exists public.crm_integration_jobs (
  id uuid primary key default gen_random_uuid(),
  provider text not null,
  job_type text,
  external_id text,
  payload jsonb,
  status text not null default 'running',
  attempts integer not null default 1,
  duration_ms integer,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ── funciones que el código llama y las migraciones no definen ───────
create or replace function public.crm_enqueue_integration_job(
  p_provider text, p_job_type text, p_external_id text default null, p_payload jsonb default null
) returns uuid language plpgsql security definer set search_path = public as $$
declare v_id uuid;
begin
  insert into public.crm_integration_jobs (provider, job_type, external_id, payload)
  values (p_provider, p_job_type, p_external_id, p_payload)
  returning id into v_id;
  return v_id;
end $$;

create or replace function public.crm_finish_integration_job(
  p_job_id uuid, p_success boolean, p_duration_ms integer default null, p_error text default null
) returns void language plpgsql security definer set search_path = public as $$
begin
  update public.crm_integration_jobs
     set status = case when p_success then 'done' else 'failed' end,
         duration_ms = p_duration_ms,
         last_error = p_error,
         updated_at = now()
   where id = p_job_id;
end $$;

-- Recalcula la señal de actividad de cada cliente a partir de su último
-- contacto observado. Las migraciones posteriores pueden reemplazarla.
create or replace function public.crm_refresh_client_engagement_signals()
returns integer language plpgsql security definer set search_path = public as $$
declare v_n integer;
begin
  update public.clientes c
     set inactivity_days = case when c.last_observed_activity_at is null then null
                                else greatest(0, (current_date - c.last_observed_activity_at::date)) end,
         engagement_signal = case
           when c.last_observed_activity_at is null then 'sin_evidencia'
           when current_date - c.last_observed_activity_at::date >= 14 then 'inactividad_14d'
           when current_date - c.last_observed_activity_at::date >= 7 then 'inactividad_7d'
           else 'actividad_reciente' end,
         updated_at = now()
   where coalesce(c.record_status, 'active') = 'active';
  get diagnostics v_n = row_count;
  return v_n;
end $$;

-- updated_at automático en las tablas base
create or replace function public.crm_set_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end $$;

do $$
declare t text;
begin
  foreach t in array array['team_members','agendas','pagos','planes_pago','plan_pago_items','clientes','crm_notification_outbox','crm_integration_jobs']
  loop
    execute format('drop trigger if exists %I_set_updated_at on public.%I', t, t);
    execute format('create trigger %I_set_updated_at before update on public.%I for each row execute function public.crm_set_updated_at()', t, t);
  end loop;
end $$;
