-- Centro de Control de cobranza. Migración aditiva y reversible.
alter table public.plan_pago_items
  add column if not exists responsable_cobranza text,
  add column if not exists estado_cobranza text not null default 'pendiente',
  add column if not exists ultimo_contacto_at timestamptz,
  add column if not exists ultimo_resultado text,
  add column if not exists promesa_pago_fecha date,
  add column if not exists proxima_accion text,
  add column if not exists proxima_accion_fecha date;

alter table public.plan_pago_items
  drop constraint if exists plan_pago_items_estado_cobranza_check;
alter table public.plan_pago_items
  add constraint plan_pago_items_estado_cobranza_check
  check (estado_cobranza in ('pendiente', 'contactado', 'promesa', 'escalado', 'incobrable', 'pagado'));

create table if not exists public.cobranza_gestiones (
  id bigint generated by default as identity primary key,
  item_id uuid not null references public.plan_pago_items(id) on delete cascade,
  responsable text not null,
  resultado text not null,
  promesa_pago_fecha date,
  proxima_accion text,
  proxima_accion_fecha date,
  estado_cobranza text not null,
  creado_por text,
  created_at timestamptz not null default now(),
  constraint cobranza_gestiones_estado_check
    check (estado_cobranza in ('pendiente', 'contactado', 'promesa', 'escalado', 'incobrable', 'pagado'))
);

create index if not exists cobranza_gestiones_item_created_idx
  on public.cobranza_gestiones(item_id, created_at desc);
create index if not exists plan_pago_items_proxima_accion_idx
  on public.plan_pago_items(proxima_accion_fecha)
  where estado = 'pendiente';

comment on table public.cobranza_gestiones is
  'Historial append-only de contactos y compromisos de cobranza.';

create or replace function public.registrar_gestion_cobranza(
  p_item_id uuid,
  p_responsable text,
  p_resultado text,
  p_promesa_pago_fecha date,
  p_proxima_accion text,
  p_proxima_accion_fecha date,
  p_estado_cobranza text,
  p_creado_por text
) returns public.plan_pago_items
language plpgsql
as $$
declare
  actualizado public.plan_pago_items;
begin
  insert into public.cobranza_gestiones (
    item_id, responsable, resultado, promesa_pago_fecha, proxima_accion,
    proxima_accion_fecha, estado_cobranza, creado_por
  ) values (
    p_item_id, p_responsable, p_resultado, p_promesa_pago_fecha, p_proxima_accion,
    p_proxima_accion_fecha, p_estado_cobranza, p_creado_por
  );

  update public.plan_pago_items set
    responsable_cobranza = p_responsable,
    estado_cobranza = p_estado_cobranza,
    ultimo_contacto_at = now(),
    ultimo_resultado = p_resultado,
    promesa_pago_fecha = p_promesa_pago_fecha,
    proxima_accion = p_proxima_accion,
    proxima_accion_fecha = p_proxima_accion_fecha
  where id = p_item_id
  returning * into actualizado;

  if actualizado.id is null then raise exception 'Item de plan no encontrado'; end if;
  return actualizado;
end;
$$;

revoke all on function public.registrar_gestion_cobranza(uuid, text, text, date, text, date, text, text)
  from public, anon, authenticated;
grant execute on function public.registrar_gestion_cobranza(uuid, text, text, date, text, date, text, text)
  to service_role;

alter table public.cobranza_gestiones enable row level security;
